image: node:12.13.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public/
    - mv build/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
